# Use root/example as user/password credentials
version: '3.1'

networks:
  ggj2023:

services:
  frontend:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/frontend.DOCKERFILE
    ports:
      - '3000:3000'
    networks:
      ggj2023:
