export default {
  levels: [
    [
      { name: 'factory', position: 0 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 0 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
    ],
  ],
  width: 20,
  height: 5,
  entities: [
    { class: 'slap-pig', position: [1, 1], args: [] },
    { class: 'slap-pig', position: [2, 1], args: [] },
    { class: 'slap-pig', position: [3, 1], args: [] },
    { class: 'slap-pig', position: [4, 1], args: [] },
    { class: 'slap-pig', position: [5, 1], args: [] },
    { class: 'slap-pig', position: [6, 1], args: [] },
    { class: 'slap-pig', position: [7, 1], args: [] },
    { class: 'slap-pig', position: [8, 1], args: [] },
    { class: 'slap-pig', position: [9, 1], args: [] },
    { class: 'slap-pig', position: [10, 1], args: [] },
    { class: 'slap-pig', position: [11, 1], args: [] },
    { class: 'slap-pig', position: [12, 1], args: [] },
    { class: 'slap-pig', position: [13, 1], args: [] },
    { class: 'slap-pig', position: [14, 1], args: [] },
    { class: 'slap-pig', position: [15, 1], args: [] },
    { class: 'slap-pig', position: [16, 1], args: [] },
    { class: 'slap-pig', position: [17, 1], args: [] },
    { class: 'slap-pig', position: [18, 1], args: [] },
    { class: 'energy-controller', position: [1, 3], args: [] },
    { class: 'player-spawner', position: [3, 3], args: [] },
    { class: 'tunnel-out', position: [5, 3], args: [] },
    { class: 'tunnel-out', position: [6, 3], args: [] },
  ],
  difficulty: 1,
};
