export default {
  levels: [
    [
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 58 },
    ],
  ],
  width: 20,
  height: 3,
  entities: [
    { class: 'slap-pig', position: [0, 0], args: [] },
    { class: 'slap-pig', position: [1, 0], args: [] },
    { class: 'slap-pig', position: [2, 0], args: [] },
    { class: 'slap-pig', position: [3, 0], args: [] },
    { class: 'slap-pig', position: [4, 0], args: [] },
    { class: 'slap-pig', position: [5, 0], args: [] },
    { class: 'slap-pig', position: [6, 0], args: [] },
    { class: 'slap-pig', position: [7, 0], args: [] },
    { class: 'slap-pig', position: [8, 0], args: [] },
    { class: 'slap-pig', position: [9, 0], args: [] },
    { class: 'slap-pig', position: [10, 0], args: [] },
    { class: 'slap-pig', position: [11, 0], args: [] },
    { class: 'slap-pig', position: [12, 0], args: [] },
    { class: 'slap-pig', position: [13, 0], args: [] },
    { class: 'slap-pig', position: [14, 0], args: [] },
    { class: 'slap-pig', position: [15, 0], args: [] },
    { class: 'slap-pig', position: [16, 0], args: [] },
    { class: 'slap-pig', position: [17, 0], args: [] },
    { class: 'slap-pig', position: [18, 0], args: [] },
    { class: 'slap-pig', position: [19, 0], args: [] },
    { class: 'tunnel-out', position: [0, 2], args: [] },
    { class: 'energy-controller', position: [2, 2], args: [] },
    { class: 'player-spawner', position: [1, 2], args: [] },
  ],
  difficulty: 1,
};
