export default {
  levels: [
    [
      { name: 'factory', position: 4 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 58 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 31 },
      { name: 'factory', position: 30 },
      { name: 'factory', position: 30 },
      { name: 'factory', position: 30 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 31 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 32 },
      { name: 'factory', position: 3 },
      { name: 'empty', position: 0 },
      { name: 'empty', position: 0 },
      { name: 'empty', position: 0 },
      { name: 'empty', position: 0 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 31 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 32 },
      { name: 'factory', position: 4 },
      { name: 'empty', position: 0 },
      { name: 'empty', position: 0 },
      { name: 'empty', position: 0 },
      { name: 'empty', position: 0 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 33 },
      { name: 'factory', position: 33 },
      { name: 'factory', position: 33 },
      { name: 'factory', position: 32 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 59 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 3 },
      { name: 'factory', position: 2 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 4 },
      { name: 'factory', position: 4 },
    ],
  ],
  width: 10,
  height: 10,
  entities: [
    { class: 'energy-controller', position: [8, 8], args: [] },
    { class: 'power-controller', position: [3, 2], args: [] },
    { class: 'storage', position: [5, 2], args: [] },
    { class: 'compactor', position: [7, 2], args: [] },
    { class: 'tunnel-out', position: [3, 6], args: [] },
    { class: 'tunnel-in', position: [2, 6], args: [] },
    { class: 'tunnel-in', position: [2, 5], args: [] },
    { class: 'tunnel-out', position: [3, 5], args: [] },
    { class: 'player-spawner', position: [7, 8], args: [] },
  ],
  difficulty: 2,
};
